<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ErrorController' => __DIR__ . '/controllers/ErrorController.php',
    'TodosController' => __DIR__ . '/controllers/TodosController.php',
    'Bootstrap'       => __DIR__ . '/Bootstrap.php',
);
