<h1>Liste des choses à faire</h1>
<p>
    <a href="/todos/new">Nouvelle chose à faire</a>
</p>
<table>
    <thead>
        <tr>
            <th>Chose à faire</th>
            <th>Date de création</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($this->todos as $todo): ?>
        <tr>
            <td><?php echo $this->escape($todo->getDescription()); ?></td>
            <td><?php echo $this->dateFormat($todo->getCreatedAt()); ?></td>
            <td><a href="/todos/edit?id=<?php echo $todo->getId(); ?>">modifier</a></td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>